# golangci-lint configuration for Freightliner project
# Focus on critical issues while allowing development flexibility

version: 2

run:
  timeout: 10m
  tests: true

linters:
  disable:
    - staticcheck
    - unused
  enable:
    - misspell

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-dirs:
    - .github
    - docs
  exclude-files:
    - ".*_test.go$"
  exclude-rules:
    - text: "SA6002.*should be pointer-like"
      linters:
        - staticcheck
