# golangci-lint configuration for Freightliner project
# Focus on critical issues while allowing development flexibility

run:
  timeout: 10m
  tests: true

linters:
  disable:
    - staticcheck
    - unused
  enable:
    - misspell
    - errcheck
    - govet
    - ineffassign

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-dirs:
    - .github
    - docs
  exclude-files:
    - ".*_test.go$"
