# Production Secrets Template
# NOTE: This file contains template secrets for production deployment
# Actual secrets should be managed through secure secret management systems
# and never committed to version control in plaintext

apiVersion: v1
kind: Secret
metadata:
  name: freightliner-api-keys
  namespace: freightliner
  labels:
    app.kubernetes.io/name: freightliner
    app.kubernetes.io/component: authentication
type: Opaque
stringData:
  api-key: "REPLACE_WITH_ACTUAL_API_KEY_HASH"  # bcrypt hashed API key
  jwt-secret: "REPLACE_WITH_ACTUAL_JWT_SECRET"  # 256-bit JWT signing secret
---
apiVersion: v1
kind: Secret
metadata:
  name: freightliner-registry-credentials
  namespace: freightliner
  labels:
    app.kubernetes.io/name: freightliner
    app.kubernetes.io/component: registry-auth
type: Opaque
stringData:
  aws-access-key-id: "REPLACE_WITH_AWS_ACCESS_KEY_ID"
  aws-secret-access-key: "REPLACE_WITH_AWS_SECRET_ACCESS_KEY"
  aws-region: "us-west-2"
  gcp-service-account-key: |
    REPLACE_WITH_GCP_SERVICE_ACCOUNT_JSON
---
apiVersion: v1
kind: Secret
metadata:
  name: freightliner-encryption-keys
  namespace: freightliner
  labels:
    app.kubernetes.io/name: freightliner
    app.kubernetes.io/component: encryption
type: Opaque
stringData:
  aws-kms-key-id: "REPLACE_WITH_AWS_KMS_KEY_ID"
  gcp-kms-key-id: "REPLACE_WITH_GCP_KMS_KEY_ID"
  gcp-key-ring: "freightliner-prod"
  gcp-key-name: "image-encryption"
---
apiVersion: v1
kind: Secret
metadata:
  name: freightliner-tls
  namespace: freightliner
  labels:
    app.kubernetes.io/name: freightliner
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_ACTUAL_TLS_CERTIFICATE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_ACTUAL_TLS_PRIVATE_KEY
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: freightliner-monitoring
  namespace: freightliner
  labels:
    app.kubernetes.io/name: freightliner
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  prometheus-password: "REPLACE_WITH_PROMETHEUS_PASSWORD"
  grafana-admin-password: "REPLACE_WITH_GRAFANA_ADMIN_PASSWORD"
  alertmanager-webhook-url: "REPLACE_WITH_ALERTMANAGER_WEBHOOK_URL"