name: 'Setup Docker Environment'
description: 'Sets up Docker Buildx with registry and caching'

inputs:
  registry-host:
    description: 'Docker registry host'
    required: false
    default: 'localhost:5100'
  setup-buildx:
    description: 'Whether to setup Docker Buildx'
    required: false
    default: 'true'
  cache-enabled:
    description: 'Whether to enable build cache'
    required: false
    default: 'true'

outputs:
  registry-host:
    description: 'Registry host that was configured'
    value: ${{ inputs.registry-host }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      if: ${{ inputs.setup-buildx == 'true' }}
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          network=host
        buildkitd-flags: |
          --allow-insecure-entitlement security.insecure
          --allow-insecure-entitlement network.host

    - name: Configure Docker registry
      shell: bash
      run: |
        echo "REGISTRY_HOST=${{ inputs.registry-host }}" >> $GITHUB_ENV
        
        # Wait for registry to be ready if using localhost
        if [[ "${{ inputs.registry-host }}" == "localhost"* ]]; then
          echo "Waiting for local registry to be ready..."
          timeout=30
          while ! curl -sf http://${{ inputs.registry-host }}/v2/ >/dev/null 2>&1; do
            if [ $timeout -eq 0 ]; then
              echo "❌ Registry not ready after 30 seconds"
              exit 1
            fi
            sleep 1
            ((timeout--))
          done
          echo "✅ Registry is ready"
        fi

    - name: Configure build cache
      if: ${{ inputs.cache-enabled == 'true' }}
      shell: bash
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "BUILDX_NO_DEFAULT_ATTESTATIONS=1" >> $GITHUB_ENV