{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "freightliner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freightliner.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "freightliner.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - {{- if .from }}
      from:
        {{- toYaml .from | nindent 8 }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- toYaml .ports | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - {{- if .to }}
      to:
        {{- toYaml .to | nindent 8 }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- toYaml .ports | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}