{{- if or .Values.secrets.awsAccessKeyId .Values.secrets.awsSecretAccessKey .Values.secrets.gcpServiceAccountKey .Values.secrets.registryAuth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freightliner.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freightliner.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.awsAccessKeyId }}
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsSecretAccessKey }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.gcpServiceAccountKey }}
  gcp-service-account-key: {{ .Values.secrets.gcpServiceAccountKey | b64enc | quote }}
  {{- end }}
  {{- range $registry, $auth := .Values.secrets.registryAuth }}
  registry-auth-{{ $registry }}: {{ $auth | b64enc | quote }}
  {{- end }}
{{- end }}