apiVersion: v1
kind: Service
metadata:
  name: {{ include "freightliner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freightliner.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
    {{- if .Values.config.metricsEnabled }}
    - port: {{ .Values.config.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "freightliner.selectorLabels" . | nindent 4 }}

---
# ClusterIP service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: {{ include "freightliner.fullname" . }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freightliner.labels" . | nindent 4 }}
    app.kubernetes.io/component: internal-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.config.metricsEnabled }}
    - port: {{ .Values.config.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "freightliner.selectorLabels" . | nindent 4 }}

---
# Headless service for StatefulSet-like behavior (if needed for clustering)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "freightliner.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freightliner.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "freightliner.selectorLabels" . | nindent 4 }}