name: CI

on:
  push:
    branches: [ main, master, develop ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: '1.24.5'
  GOLANGCI_LINT_VERSION: 'v1.64.2'
  PIPELINE_MONITORING: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Verify dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Format check
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "Code is not formatted. Please run 'gofmt -w .'"
            gofmt -l .
            exit 1
          fi

      - name: Validate golangci-lint config
        run: |
          echo "Checking golangci-lint configuration..."
          if [[ -f ".golangci.yml" ]] || [[ -f ".golangci.yaml" ]]; then
            echo "✓ golangci-lint config found"
          else
            echo "ℹ No custom golangci-lint config (using defaults)"
          fi

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout=5m --verbose

  security:
    name: Security
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Security scan
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -no-fail -fmt sarif -out gosec-results.sarif ./...

      - name: Upload security results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec-results.sarif
        continue-on-error: true

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [test, lint]  # Run after tests pass
    if: >
      github.event_name == 'pull_request' ||
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/main' ||
      contains(github.event.head_commit.message, '[docker]')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pre-build validation
        run: |
          echo "Validating Dockerfile..."
          if [[ ! -f "Dockerfile" ]]; then
            echo "Error: Dockerfile not found"
            exit 1
          fi
          
          echo "Checking Docker daemon..."
          docker info
          
          echo "Disk space check..."
          df -h

      - name: Build multi-stage image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: build  # Build stage for CI validation
          push: false
          tags: freightliner:build-stage
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Build production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: freightliner:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Test image functionality
        run: |
          echo "Testing image functionality..."
          
          # Test version command
          if docker run --rm freightliner:test --version; then
            echo "✓ Version command works"
          else
            echo "⚠ Version command not available (acceptable)"
          fi
          
          # Test help command
          if docker run --rm freightliner:test --help >/dev/null 2>&1; then
            echo "✓ Help command works"
          else
            echo "✗ Help command failed"
            exit 1
          fi
          
          # Test container startup and shutdown
          echo "Testing container lifecycle..."
          CONTAINER_ID=$(docker run -d freightliner:test sleep 5)
          sleep 2
          if docker ps | grep -q "$CONTAINER_ID"; then
            echo "✓ Container started successfully"
            docker stop "$CONTAINER_ID" >/dev/null
            docker rm "$CONTAINER_ID" >/dev/null
          else
            echo "✗ Container failed to start"
            exit 1
          fi

      - name: Image security scan
        run: |
          echo "Running basic security checks..."
          
          # Check image size
          IMAGE_SIZE=$(docker images freightliner:test --format "{{.Size}}")
          echo "Image size: $IMAGE_SIZE"
          
          # Check for non-root user
          USER_CHECK=$(docker run --rm freightliner:test whoami 2>/dev/null || echo "unknown")
          if [[ "$USER_CHECK" != "root" ]]; then
            echo "✓ Running as non-root user: $USER_CHECK"
          else
            echo "⚠ Running as root user (security concern)"
          fi
          
          # Basic vulnerability scan (if available)
          if command -v trivy &> /dev/null; then
            echo "Running Trivy security scan..."
            trivy image --exit-code 0 --severity HIGH,CRITICAL freightliner:test
          else
            echo "Trivy not available, skipping vulnerability scan"
          fi

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up Docker resources..."
          docker rmi freightliner:test freightliner:build-stage || true
          docker system prune -f || true